### ISSUE TITLE
Feature Request: Manual and sample project for the model generator

### ISSUE THREAD

**Issue by ErikKoppenhagen** [kieler/osgiviz#10]
Afaik, the model generator is now included in this open source project. So the manual should migrate, too. Additionally, a small sample project containing a small OSGi application with a pom.xml tho generate the model would provide a great help starting to use this tool.

**Comment by NiklasRentzCAU** [comment]
Additionally, the model generator needs to be included in the build so that anyone can use it for arbitrary osgi projects via the Maven Mojo or via a simple command line program, if the tool should not be included in the main pom files of the project. This is on my TODO list to be tackled quite soon.

And which manual are you talking about? There already is a (only german) manual on how to use the tool [here](https://github.com/OpenKieler/osgiviz/tree/master/plugins/de.scheidtbachmann.osgimodel.model.generate). That manual does not work yet however, as the build does not include the bundle and publish any Maven artifact for that yet.

**Comment by ErikKoppenhagen** [comment]
Yes, i had the manual you have linked in mind. I would suggest to include this on the landing page of OSGiViz, too.

**Comment by NiklasRentzCAU** [comment]
The model generator is now included in the build as a CLI tool with a automatically build jar that can be used. The Maven Mojo is not really included yet, as there are no plans yet to release it on maven central yet, for now it just will stick around here in the repository as well next to the supported CLI tool for model generation. The manual for that generator is now updated to the supported use case and included in the main manual of the project.

Still missing for this ticket: The sample OSGi project.

**Comment by NiklasRentzCAU** [comment]
Example code added with [this commit ](https://github.com/kieler/osgiviz/commit/72a965ddf432245a4864981aa261c776ac21a502) and example models with [this one](https://github.com/kieler/osgiviz/commit/fdb2f445c16ffd018b59a072a15de408a9a6e256).
